### PR TITLE
fix!: improve performance of stack order evaluation

### LINKED ISSUE #2164: [BUG] Performances issues due to a high number of tags
**Performances issues**
When we want to run a simple command `terramate run` or `terramate script run` the command will hang and maybe wil provide a return (after 5 minutes, I stop the command).
We use the tags for differents things : ordering + managing providers and generating required.providers.tf properly.

**To Reproduce**

1. Given context, see attachments. 
2. Run command `terramate list` and see it returns almost immediately
3. Run command `terramate list --run-order` and see the command will hang

**Expected behavior**
The command will return in a timely manner.

**Log Output**
We don't have any logs for this error, even the verbose command does not provide any more output.

**Environment (please complete the following information):**
 - OS: Linux
 - OS Version Ubuntu 20.04
 - Git Version 2.49.0
 - Terramate Version 0.13.2

**Additional context**

Attachment 1 : `terramate debug show metadata`

[terramate-debug-show-metadata-result.txt](https://github.com/user-attachments/files/20879364/terramate-debug-show-metadata-result.txt)

### PR DESCRIPTION
**Pull request by snakster**
## What this PR does / why we need it:

This PR improves the graph traversal algorithm to determine the stack run order, because it would scale poorly for graph layouts with many edges. Such graphs would typically result when using tags and before/after.

As a result of changing the traversal algorithm, the order for unrelated stacks may change.
Before, it was a DFS traversal, now its BFS. See changelog for some examples.

## Which issue(s) this PR fixes:

Fixes #2164 

## Does this PR introduce a user-facing change?

```
Yes, it changes the run order between unrelated stacks.
```

### CODE REVIEW

File: e2etests/core/exp_run_graph_test.go [hunk 1]
```diff
@@ -175,7 +175,7 @@ func TestOrderGraphAfter(t *testing.T) {
 				digraph  {n1[label="stack-a"];
 					n2[label="stack-b"];
 					n1->n2[color="red"];
-					n2->n1;
+					n2->n1[color="red"];
```
Comment (snakster) [inline e2etests/core/exp_run_graph_test.go:178]: Cycles are now shown in more edges in the graph. Here we have a cycle a->b->a, and both edges are red. I think the new one is more correct than it was before, but this is just for debugging.

File: run/dag/dag.go [hunk 2]
```diff
@@ -98,26 +102,26 @@ func (d *DAG[V]) addAncestor(node, ancestor ID) {
...
 // Reduce removes nodes that match the given predicate.
 // When a node is removed, all edges to it are replaced by edges to its children,
 // so the order within the graph is preserved.
+// May only be called after Validate().
 func (d *DAG[V]) Reduce(predicate func(id ID) bool) {
-	visited := Visited{}
-
 	shouldRemove := make(map[ID]bool, len(d.dag))
-	ids := d.IDs()
+	ids := d.Order()
```
Comment (snakster) [inline run/dag/dag.go:124]: Reducing means if we identify nodes b and c to be removed, we re-connect the graph so that
a <- b <- c <- d
=>
a <- d

Doing this from "left to right" by using Order(), which is the similiar behaviour as the walkFrom before would do.

File: run/dag/dag.go [hunk 3]
```diff
@@ -153,6 +150,14 @@ func (d *DAG[V]) Reduce(predicate func(id ID) bool) {
 			delete(d.values, id)
 		}
 	}
+
+	newOrder := make([]ID, 0, len(d.order))
```
Comment (snakster) [inline run/dag/dag.go:155]: Order sequence is cached. We do not have to re-compute it after we removed nodes, we just remove the nodes from the cached order.

File: run/dag/dag_test.go [hunk 4]
```diff
@@ -222,6 +222,7 @@ func dagTests() []testcase {
 				"B": {
 					ancestors: []dag.ID{"C", "D"},
 				},
+				"C": {},
```
Comment (snakster) [inline run/dag/dag_test.go:225]: This was a bug in the test case. The old algorithm coincidentally supported it even even you referenced nodes that were never added with `AddNode`, but this has no use case and just complicates everything.

File: run/dag/dag_test.go [hunk 5]
```diff
@@ -404,6 +405,9 @@ func TestTransformDAG(t *testing.T) {
 		))
 	}
 
+	_, err := a.Validate()
```
Comment (snakster) [inline run/dag/dag_test.go:408]: We always need the validate now.
1. Add nodes
2. Validate (which computes order and detects cycles)
3. Order, Reduce, etc

Before validate was optional.

File: run/dag/dag.go [hunk 6]
```diff
@@ -98,26 +102,26 @@ func (d *DAG[V]) addAncestor(node, ancestor ID) {
 
 // Validate the DAG looking for cycles.
 func (d *DAG[V]) Validate() (reason string, err error) {
-	d.cycles = make(map[ID]bool)
-	d.validated = true
-
-	for _, id := range d.IDs() {
+	d.calcTopologicalOrder()
+	for _, id := range slices.Sorted(maps.Keys(d.cycles)) {
```
Comment (snakster) [inline run/dag/dag.go:106]: `validateNode` will still be non-optimized, but now we only call it on nodes where we already know that we have a cycle, and it stops once we found one.

The `calcTopologicalOrder` marks cycles, but doesn't calculate the paths.

**Review by snakster — COMMENTED** [review]
🦆

File: run/dag/dag.go [hunk 7]
```diff
@@ -227,33 +232,82 @@ func (d *DAG[V]) HasCycle(id ID) bool {
...
+	if !d.validated {
+		panic(errors.E(errors.ErrInternal, "please report this as a bug"))
+	}
+	return d.order
+}
+
+// calcTopologicalOrder does topological ordering based on Kahns algorithm
+func (d *DAG[V]) calcTopologicalOrder() {
+	// Helper maps to lookup predecessors and successors of a node.
+	// Roots of the grph are nodes with no predecessors.
```
Comment (sixstone-qq) [inline run/dag/dag.go]:
```suggestion
	// Roots of the graph are nodes with no predecessors.
```

File: run/dag/dag.go [hunk 8]
```diff
@@ -227,33 +232,82 @@ func (d *DAG[V]) HasCycle(id ID) bool {
...
+	}
+
+	// Will contain the topological order.
+	order := []ID{}
 
-			visited[id] = struct{}{}
-		})
+	// Temporary set that contains nodes without predecessors for the algorithm.
+	// Will be expanded as we remove edges.
+	s := []ID{}
```
Comment (sixstone-qq) [inline run/dag/dag.go]: As I read, it may be better to rename the variable to queue for better readability?
```suggestion
	queue := []ID{}
```

File: run/dag/dag.go [hunk 9]
```diff
@@ -227,33 +232,82 @@ func (d *DAG[V]) HasCycle(id ID) bool {
...
+			delete(predMap[succ], n)
+			delete(succMap[n], succ)
+
+			// If succ is now without predecessors, it will be added to s next.
+			if len(predMap[succ]) == 0 {
+				next = append(next, succ)
+			}
+		}
+
+		// Add in a deterministic manner.
```
Comment (sixstone-qq) [inline run/dag/dag.go]:
```suggestion
		// Add using lexicographical order to be deterministic.
```

File: run/dag/dag.go (hunk 3 above)
Comment (sixstone-qq) [reply run/dag/dag.go:155]: Could we do this in the previous `for` loop? Or does not help this optimisation to read it better.

**Review by sixstone-qq — COMMENTED** [review]
Just few comments that may improve the PR.

Great work! :people_hugging:

File: run/dag/dag.go (hunk 7 above)
Comment (snakster) [reply run/dag/dag.go]: Fixed in [e623fed](https://github.com/terramate-io/terramate/pull/2165/commits/e623fed5c4b669bf1da740756ede97c6f733374a)

File: run/dag/dag.go (hunk 8 above)
Comment (snakster) [reply run/dag/dag.go]: Agreed, done in [e623fed](https://github.com/terramate-io/terramate/pull/2165/commits/e623fed5c4b669bf1da740756ede97c6f733374a).

File: run/dag/dag.go (hunk 9 above)
Comment (snakster) [reply run/dag/dag.go]: Done in [e623fed](https://github.com/terramate-io/terramate/pull/2165/commits/e623fed5c4b669bf1da740756ede97c6f733374a)

File: run/dag/dag.go (hunk 3 above)
Comment (snakster) [reply run/dag/dag.go:155]: You are right, it could be refactored a bit, but I also think it's ok like this. Added an extra comment in [e623fed](https://github.com/terramate-io/terramate/pull/2165/commits/e623fed5c4b669bf1da740756ede97c6f733374a)

**Review by sixstone-qq — APPROVED** [review]
