### PR TITLE
fix(generate): dotfiles must not be ignored while detecting existing files.

### LINKED ISSUE #1260: [BUG] `generate_hcl` doesn't detect dotted files
**Describe the bug**
If `generate_hcl`'s label starts with a dot the files are always generated and if the condition is unmet the files are remaining also. Seems like Terramate isn't aware of these files at all hence the generation always.

On the other side `generate_file` behaves exactly as expected.

**To Reproduce**

```
waxb@mbp:terramate-bug$ tree -a
.
├── stack.tm.hcl
├── terramate.tm.hcl
└── test.tm.hcl

1 directory, 3 files
waxb@mbp:terramate-bug$ cat test.tm.hcl 
globals {
  to_generate = true
}

generate_hcl ".file.hcl" {
  condition = global.to_generate
  content {}
}

generate_hcl ".directory/file.hcl" {
  condition = global.to_generate
  content {}
}

generate_file ".file" {
  condition = global.to_generate
  content = ""
}

generate_file ".directory/file" {
  condition = global.to_generate
  content = ""
}
waxb@mbp:terramate-bug$ terramate generate 
Code generation report

Successes:

- /
	[+] .directory/file
	[+] .directory/file.hcl
	[+] .file
	[+] .file.hcl

Hint: '+', '~' and '-' mean the file was created, changed and deleted, respectively.
waxb@mbp:terramate-bug$ tree -a
.
├── .directory
│   ├── file
│   └── file.hcl
├── .file
├── .file.hcl
├── stack.tm.hcl
├── terramate.tm.hcl
└── test.tm.hcl

2 directories, 7 files
waxb@mbp:terramate-bug$ terramate generate 
Code generation report

Successes:

- /
	[+] .directory/file.hcl
	[+] .file.hcl

Hint: '+', '~' and '-' mean the file was created, changed and deleted, respectively.
waxb@mbp:terramate-bug$ terramate generate 
Code generation report

Successes:

- /
	[+] .directory/file.hcl
	[+] .file.hcl

Hint: '+', '~' and '-' mean the file was created, changed and deleted, respectively.
waxb@mbp:terramate-bug$ tree -a
.
├── .directory
│   ├── file
│   └── file.hcl
├── .file
├── .file.hcl
├── stack.tm.hcl
├── terramate.tm.hcl
└── test.tm.hcl

2 directories, 7 files
waxb@mbp:terramate-bug$ sed -i 's/true/false/' test.tm.hcl 
waxb@mbp:terramate-bug$ terramate experimental get-config-value global.to_generate
false
waxb@mbp:terramate-bug$ terramate generate 
Code generation report

Successes:

- /
	[-] .directory/file
	[-] .file

Hint: '+', '~' and '-' mean the file was created, changed and deleted, respectively.
waxb@mbp:terramate-bug$ terramate generate 
Nothing to do, generated code is up to date
waxb@mbp:terramate-bug$ tree -a
.
├── .directory
│   └── file.hcl
├── .file.hcl
├── stack.tm.hcl
├── terramate.tm.hcl
└── test.tm.hcl

2 directories, 5 files
```

**Expected behavior**
Generation of hcl files starting with a dot.

**Environment (please complete the following information):**
 - OS: macOS
 - OS Version: Ventura 13.5
 - Git Version:  2.42.0
 - Terramate Version: 0.4.3
🎂

### PR DESCRIPTION
**Pull request by i4ki**
## What this PR does / why we need it:

The `generator` was ignoring dot dirs/files while scanning the project for the detection of existing/changed/deleted files.
The issue existed since `v0.1.36` version, introduced in PR [#624](https://github.com/terramate-io/terramate/commit/51221de238bdd06668421f9d5427351d9724ff4a#diff-39a24c8d3907e38beb5e39b5f0a40df7aa73c38449615f140ec3fca502900e86R297).

## Which issue(s) this PR fixes:

Fixes #1260 

## Does this PR introduce a user-facing change?
```
yes, it fixes a generate bug where dot files were always showing as "created" even if already in the disk.
```

### CODE REVIEW

File: generate/generate_test.go [hunk 1]
```diff
@@ -709,6 +709,144 @@ func TestGenerateConflictsBetweenGenerateTypes(t *testing.T) {
 				},
 			},
 		},
+		{
+			// https://github.com/terramate-io/terramate/issues/1260
+			// dotfiles should not be ignored if not inside a .tmskip
+			name: "regression test: generating dotfiles do not recreate all the time",
```
Comment (snakster) [inline generate/generate_test.go:715]: I think this test is in the wrong function `TestGenerateConflictsBetweenGenerateTypes`. It doesn't affect the outcome, but it's mislabeled since the other test cases in this function are conflict-themed.

Comment (i4ki) [reply generate/generate_test.go:715]: yep, thanks for catching this!

**Review by snakster — APPROVED** [review]
👍
