### PR TITLE
fix: use unbuffered IO for non-cloud, non-parallel run

### LINKED ISSUE #2208: [BUG] Last line of run command is not flushed on console
**Describe the bug**
Since terramate 0.14, the last output of run command is not flushed anymore.

**To Reproduce**

Use terramate 0.14.5

1. use terramate 0.14.5, have a stack (here demo)
2. Run command `terramate run --tags demo bash -c 'read -s -p "Enter a word: "'`
3. No output before the end of the execution

```shell
terramate run --tags demo bash -c 'read -p "Enter a word: "'
terramate: Entering stack in /stacks/demo
terramate: Executing command "bash -c read -p \"Enter a word: \""
Hello
Enter a word:
```

**Expected behavior**

Before 0.14 (on 0.13.3) the last line was displayed (it's easier to handle terraform prompt confirmation).

For the same example:
```
terramate run --tags demo bash -c 'read -p "Enter a word: "'
terramate: Entering stack in /stacks/demo
terramate: Executing command "bash -c read -p \"Enter a word: \""
Enter a word: Hello
```

**Log Output**
n/a

**Environment (please complete the following information):**
 - OS: Linux 5.15.133.1-microsoft-standard-WSL2
 - OS Version: Ubuntu 22.04.4 LTS
 - Git Version: 2.34.1
 - Terramate Version: 0.14.5

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by snakster**
## What this PR does / why we need it:

This PR fixes the regression described in #2208 , which was introduced in #2184 .

The fix itself is simple, the remaining changes in the PR are about extending our testing code to allow creating a testcase to reproduce the regression.

The test cases also showed that there is still some non-deterministic behaviour when using interactive input combined with cloud sync buffered output. I was not yet able to understand if this is caused by the testing code or Terramate itself - either way, it is not supported for now.

## Which issue(s) this PR fixes:

Fixes #2208 

## Notes

To enable interactive I/O for the test runner, I used pipes, which keeps the code simple (instead of polling).
I kept the old functionality of using a buffer for non-interactive tests, which are basically all of them, because I was concerned that switching to pipes for everything could have a performance impact and make the tests slower.

## Does this PR introduce a user-facing change?

```
yes, see changelog
```

---

> [!NOTE]
> Use unbuffered stdout/stderr for run/script when single-threaded and not syncing to Cloud; overhaul test runner for interactive I/O and add coverage.
> 
> - **Engine (run)**:
>   - Use direct (unbuffered) `Stdout/Stderr` for child commands when not syncing to Terramate Cloud and `--parallel=1`.
>   - Retain line-buffered output only for Cloud sync or `--parallel>1`; add `waitForBuffersFunc` to synchronize buffer flushing on exit paths.
> - **E2E Test Runner**:
>   - Introduce `CmdIOMode` (pipe vs buffer) and exported concurrency-safe `Buffer`.
>   - Add `RunInteractive` with step-by-step stdin/stdout/stderr handling; refactor `NewCmd`, `Run`, and `RunWithStdin` to support new IO modes.
>   - Update signal fixtures and helpers to use new `Buffer` API.
> - **Tests**:
>   - Add `helper prompt` command for interactive prompts.
>   - New tests: `TestRunIOBuffering` and `TestScriptRunIOBuffering` validating unbuffered behavior (and buffering in parallel/cloud cases).
> - **Meta**:
>   - CHANGELOG: add Unreleased section describing new IO buffering behavior and notes/limitations.
>   - Bump VERSION to `0.14.7-dev`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 5660bb74c9c722b0537413d24eba608c9b80ec5d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: engine/run.go [hunk 1]
```diff
@@ -458,21 +458,28 @@ func (e *Engine) RunAll(
 			cmd.Dir = run.Stack.HostDir(e.Config())
 			cmd.Env = environ
 
+			isCloudSync := e.IsCloudEnabled() && opts.Hooks.LogSyncCondition(task, run)
```
Comment (snakster) [inline engine/run.go:461]: 🦆  This file is the fix, everything else is for testing.

File: e2etests/internal/runner/runner_signal_fixture.go [hunk 2]
```diff
@@ -102,7 +102,7 @@ func (run *RunFixture) Run() RunResult {
 		t.Fatalf("unexpected run mode: %d", run.mode)
 	}
 
-	exec := run.cli.NewCmd(args...)
+	exec := run.cli.NewCmd(false, args...)
```
Comment (sixstone-qq) [inline e2etests/internal/runner/runner_signal_fixture.go]: _nitpick_ I would say to use constants for booleans here to improve readability but not important.
```suggestion
	exec := run.cli.NewCmd(noInteractive, args...)
```

**Review by sixstone-qq — APPROVED** [review]
Great work on testing! :people_hugging:

File: e2etests/internal/runner/runner_signal_fixture.go (hunk 2 above)
Comment (snakster) [reply e2etests/internal/runner/runner_signal_fixture.go]: Done in [cd452d3](https://github.com/terramate-io/terramate/pull/2217/commits/cd452d3eb2d2852fcd0f68459341a07e85dd6414)

**Review by sixstone-qq — DISMISSED** [review]

File: e2etests/core/run_test.go [hunk 3]
```diff
@@ -3340,6 +3340,66 @@ stack "/stack":
...
+			stdin("my input\n")
+			expectStdout("\nyou entered: my input\n")
+		}
+
+		result := cli.RunInteractive(ioFunc, runArgs...)
+
+		AssertRunResult(t, result, RunExpected{})
+	})
+
+	// TODO(snk): This test is non-deterministic on CI. Investigate why.
```
Comment (snakster) [inline e2etests/core/run_test.go:3375]: I disabled this test after it was producing non-deterministic results in CI. It could be investigated in the future, but it shouldn't be a blocker for the fix that is tested above (`non-cloud, non-parallel is unbuffered`).

**Review by sixstone-qq — APPROVED** [review]
